export const COVER_LETTER_TEMPLATE_FR = `
{{CANDIDATE_FULL_NAME}}
{{CANDIDATE_ADDRESS_LINE1}}
{{CANDIDATE_ZIP}} {{CANDIDATE_CITY}}
{{CANDIDATE_PHONE}}

{{COMPANY_NAME}}
Ressources Humaines
{{COMPANY_ADDRESS_LINE1}}
{{COMPANY_ZIP}} {{COMPANY_CITY}}

{{CITY}}, le {{DATE}}

{{ROLE_TITLE}}

Madame, Monsieur,

{{OPENING_PARAGRAPH}}

{{EXPERIENCE_PARAGRAPH}}

{{ACHIEVEMENTS_PARAGRAPH}}

{{CLOSING_PARAGRAPH}}

{{FORMAL_CLOSING}}

{{CANDIDATE_FULL_NAME}}

Annexes : CV, diplômes, certificats de travail
`.trim();

export const COVER_LETTER_TEMPLATE_EN = `
{{CANDIDATE_FULL_NAME}}
{{CANDIDATE_ADDRESS_LINE1}}
{{CANDIDATE_ZIP}} {{CANDIDATE_CITY}}
{{CANDIDATE_PHONE}}

{{COMPANY_NAME}}
Human Resources
{{COMPANY_ADDRESS_LINE1}}
{{COMPANY_ZIP}} {{COMPANY_CITY}}

{{CITY}}, {{DATE}}

{{ROLE_TITLE}}

Dear Hiring Manager,

{{OPENING_PARAGRAPH}}

{{EXPERIENCE_PARAGRAPH}}

{{ACHIEVEMENTS_PARAGRAPH}}

{{CLOSING_PARAGRAPH}}

{{FORMAL_CLOSING}}

{{CANDIDATE_FULL_NAME}}

Attachments: CV/Resume, diplomas, work certificates
`.trim();
